// <auto-generated />
namespace WazniakWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class validators_changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validators_changed));
        
        string IMigrationMetadata.Id
        {
            get { return "201312111752255_validators_changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
